### ISSUE TITLE
Missing dependency on fresh x86_gcc2 builder

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haiku-kitchen#11]
**Issue**

On a new builder, every port failed due to kitchen not downloading libpng16 needed for freetype.

**Workaround**

Manually download https://vmpkg.haiku-os.org:5825/libpng16-1.6.29-2-x86_gcc2.hpkg into haikuports packages directory on builder.

**Comment by waddlesplash** [comment]
It sounds like you need to run a `pkgman full-sync` on the builder; libpng16 should be part of system packages...

**Comment by waddlesplash** [comment]
Appears to have it now? http://vmpkg.haiku-os.org/#/build/47
