### ISSUE TITLE
Remote builder recovery.

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haiku-kitchen#13]
Had a qemu builder go up to 100% cpu and lock up. Looks as though the git repo got corrupted which caused kitchen to show a red x for the builder post=reboot.

![b_error](https://user-images.githubusercontent.com/100110/28602222-6b25babe-7182-11e7-9049-062261e9f517.png)

It might be nice to have a remote "reset" call to erase the build directories and reconfigure the node.

![error](https://user-images.githubusercontent.com/100110/28602183-47ad356c-7182-11e7-99ad-c9648a47f49f.png)

**Comment by waddlesplash** [comment]
Yeah, I should implement something like that, indeed.
