### ISSUE TITLE
Please start adding unit tests

### ISSUE THREAD

**Issue by leavengood** [haikuports/haiku-kitchen#5]
This is a whole lot of code without any tests. Both the client and server should have a good test suite.

**Comment by leavengood** [comment]
Before you spend too much time on this though, I would flesh out more of the system. But any new work would probably benefit from unit tests, especially something where you are having a lot of trouble (like file transfers.)

**Comment by waddlesplash** [comment]
Well, the problem there turned out to be a race condition, which unit tests tend to not help with very much... But stuff like `Recipe` it's easy to add unit tests for, so I'm doing that now.

**Comment by leavengood** [comment]
Just focus on best bang for the buck, testing things with a lot of branches, etc.

**Comment by waddlesplash** [comment]
Recipe tests were added in 6850babd65dcd973f753279e577489701c649d9f, I think that's good enough for now. (Looks like I forgot to close this then...)
