### ISSUE TITLE
Prefix argument

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haiku-kitchen#7]
Haikuporter buildmaster has a flag to choose the prefix path for data storage. It would be nice if kitchen had this.

Example:
```
   node index.js --prefix=./data
   node index.js --prefix=/builds/data
```

**Comment by waddlesplash** [comment]
Not an easy refactor. My intention was just to symlink `data` to the data storage location.

**Comment by waddlesplash** [comment]
Yeah, closing as WONTFIX, symlinking works just fine.
